version: '3.8'

services:
  backend:
    build: ./server
    environment:
      - NODE_ENV=production
    env_file:
      - ./server/.env
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build: ./client
    ports:
      - "8080:8080"
    depends_on:
      - backend

  db:
    build: ./db
    env_file:
      - ./server/.env
    ports:
      - "5432:5432"
